### ISSUE TITLE
Can this module purge/remove unwanted/unmanaged repos?

### ISSUE THREAD

**Issue by salderma** [voxpupuli/puppet-yum#104]
Hi

As the subject implies, I'm looking for a way to ensure that puppet manages all the yum repos on a system.  I like that this module provides a group install feature, but it seems like it does not have the option to purge unmanaged repos.  Is that correct?

Thanks!

**Comment by SimonHoenscheid** [comment]
Same question here

**Comment by ekohl** [comment]
I think this just uses the `yumrepo` resource so the following will probably work:
```puppet
resources { 'yumrepo':
  purge => true,
}

**Comment by TJM** [comment]
See #94

**Comment by ThoTischner** [comment]
#94 Updated with workaround for the mean time.

**Comment by kenyon** [comment]
Duplicate of #94.
