### ISSUE TITLE
Centos 6 support broken

### ISSUE THREAD

**Issue by oniGino** [voxpupuli/puppet-yum#198]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: all
- Ruby:
- Distribution: centos 6
- Module version: latest 

Replace mirrorlist for centos6 with
baseurl=http://vault.centos.org/6.10/os/$basearch/
to fix issue

see
https://www.getpagespeed.com/server-setup/how-to-fix-yum-after-centos-6-went-eol

**Comment by TheMeier** [comment]
CentOS 6 is EOL.

**Comment by oniGino** [comment]
> CentOS 6 is EOL.

thats correct, exactly why you need to update your project code to point to the repo archive.

just because a distro is EOL doesnt mean environments magically stop running it.

**Comment by TheMeier** [comment]
Actually it is quite common to simply remove support for EOL platforms. I was just about to work on a PR for that...

**Comment by TJM** [comment]
@oniGino You can supply alternate repo URLs in hieradata if you need to support an EOL platform (or, in my case, if you can't reach the Internet and have to supply an internal server), but support for CentOS6 should be removed from this module, and definitely should not be re-pointed to archive. Stuff *breaking* may be the only way some admins know they have an EOL OS running and they are not actually receiving updates for it. :)

Technically, the removal should have been done over 6 months ago, oops.

**Comment by oniGino** [comment]
Your choice.
Thanks, we already have overloaded the hieradata for this.

But I would say, as someone managing a 500+ node puppet environment, where I do not always have control over distro versions, formally dropping support in your docs or referencing vault for older distros might prove helpful for others as well.
