### ISSUE TITLE
 yum::config fails with comma separated values

### ISSUE THREAD

**Issue by matonb** [voxpupuli/puppet-yum#21]
### Affected Puppet, Ruby, OS and module versions/distributions

- Puppet:             4.8.0
- Ruby:                ruby 2.1.9p490 (2016-03-30 revision 54437) [x86_64-linux]
- Distribution:      OEL Linux 7.3
- Module version: 0.9.15

### How to reproduce (e.g Puppet code you use)
Give a yum::config resources a comma separated value e.g.

    yum::config{'exclude':
      ensure => 'kernel, kernel-uek',
    }

### What are you seeing

    Error: /Stage[main]/Profile_base::Linux::Yum/Yum::Config[exclude]/Augeas[yum.conf_main_exclude]: Could not evaluate: Saving failed, see debug

### What behaviour did you expect instead

    exclude=kernel, kernel-uek

in /etc/yum.conf

### Any additional information you'd like to impart

https://ask.puppet.com/question/17826/using-commas-in-augeas-set-commands/

Maybe accept an array of values

    yum::config{'exclude':
      ensure => [ 'kernel', 'kernel-uek' ],
    }
So that augeas vaues can be correctly defined ?

**Comment by bastelfreak** [comment]
Hi @matonb. thanks for the bugreport. Are you able to provide a patch for this?

**Comment by matonb** [comment]
Sure.
After poking around with augtool it turns out to be much simpler than anticipated.
See PR #29

**Comment by bastelfreak** [comment]
closing this since we pushed the fix
