### ISSUE TITLE
Yumrepo provider fork?

### ISSUE THREAD

**Issue by lamawithonel** [voxpupuli/puppet-yum#32]
I'm planning on forking the `Yumrepo` `inifile` provider from upstream. I know Puppet, Inc. will accept patches, but I want to move faster than their release cycle. Is this something the project is open to hosting/supporting? If not I can take it elsewhere, but I imagine Puppet, Inc. is eager to rid themselves of the type/provider in some future major release and this seems like an obvious place to maintain a successor.

**Comment by vinzent** [comment]
the same issue could probably (hypotetically) arise with puppet-selinux and the selmodule type.  

for example EL7.3 introduced a breaking change and broke some selmodule  functionality. The ability to provider a faster fix would have been desireable.

**Comment by lamawithonel** [comment]
My priorities have changed and I no longer have time to work on this. I'm closing it for my own sake.
