### ISSUE TITLE
Fix versionlock regex

### ISSUE THREAD

**Issue by lamawithonel** [voxpupuli/puppet-yum#35]
The current regular expressions for the `yum::versionlock` defined type are too liberal and will match invalid strings as long as they end in an asterisk. In my experience, although the official documentation is a little vague on this, wildcard characters cannot cover the field separators.  For example, `0:bash-4.1.2-9.el6_2.*`, the example from the header docs, is valid, because it uses the wildcard to cover the `%{ARCH}` field. However, this seemingly similar input would be invalid to yum-versionlock (but valid to the module): `0:bash-4.1.2-9*`.

Fixing this will be a breaking change, so I wanted to open this before it gets tagged `1.0.0`. I am working on a fix.

**Comment by vinzent** [comment]
it's too my expirience that the asterisk only works for a single field and documentation is not very good.
