### ISSUE TITLE
Remove individual configs from init.pp, use create_resources pattern instead

### ISSUE THREAD

**Issue by lamawithonel** [voxpupuli/puppet-yum#36]
Rather than including lots of individual calls to `yum::config`, the init class should use a [`create_resources()` pattern](https://docs.puppet.com/puppet/latest/lang_resources_advanced.html#implementing-the-createresources-function) with current defaults defined in module data. This would be a breaking change.

**Comment by vinzent** [comment]
this seems to me a good case for puppet 4 each loop: https://docs.puppet.com/puppet/latest/lang_iteration.html#examples
