### ISSUE TITLE
Class[Yum]: has no parameter named 'config_options'

### ISSUE THREAD

**Issue by weijianwen** [voxpupuli/puppet-yum#48]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.10.0
- Ruby: shippe with Puppet
- Distribution: Cent OS 7
- Module version: 1.0.0

## How to reproduce (e.g Puppet code you use)

Install `puppet-yum`:

```
# puppet module install puppet-yum
```

Assign `yum` module to all nodes in `site.pp` on puppetserver:

```
node default {

    class { 'yum':
      keep_kernel_devel => true,
      clean_old_kernels => true,
      config_options    => {
          my_cachedir => {
            ensure => '/home/waldo/.local/yum/cache',
            key    => 'cachedir',
          },
          gpgcheck    => true,
          debuglevel  => 5,
          assumeyes   => {
            ensure => 'absent',
          },
        },
    }

}
```

Apply yum setting on the client node:

```
client# cat /dev/null > /etc/yum.conf; puppet agent --verbose --debug -t
```

## What are you seeing

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error wh
ile evaluating a Resource Statement, Class[Yum]: has no parameter named 'config_options' at /etc/puppetlabs/code/en
vironments/production/manifests/site.pp:3:5 on node mu05.
```

## What behaviour did you expect instead

Yum settings should be applied on to the client node.

## Any additional information you'd like to impart

The settings above come from `puppet-yum`'s README. On pupetforge page, `config_options` usage is not documented yet. https://forge.puppet.com/puppet/yum

**Comment by domcleal** [comment]
> The settings above come from puppet-yum's README. On pupetforge page, config_options usage is not documented yet. https://forge.puppet.com/puppet/yum

If you're using the version from git then the README in the repository's correct. If you're using the Forge version 1.0.0 though, follow the README on the Forge.

1.0.0 doesn't have `config_options`, use `yum::config` instead: https://forge.puppet.com/puppet/yum#yumconfig

**Comment by weijianwen** [comment]
Thanks for the clearification.
