### ISSUE TITLE
how does the module get the name of the package?

### ISSUE THREAD

**Issue by hdwiv00** [voxpupuli/puppet-yum#50]
Hello,
 i have couple of basic questions about installing using this module. 
Q1. How does the module get he package name? for example i need to install rng-tools, what is the proper package name that i should provide?
Q2. How do i install multiple packages with the same name? 
for example i have libgcc++ for x86_64 and i686  and i need to install both of them but i can't provide the same package name as it errors out. 
Any inputs will be helpful.
thanks,
haim.

**Comment by joekohlsdorf** [comment]
This module primarily aims to manage yum repositories, it is not meant as a way to install packages with the yum package manager.
To install packages you can for example use the function ```ensure_packages()``` from ```puppetlabs/stlib``` which is independent of the package manager your OS uses.
