### ISSUE TITLE
EPEL managed_repo broken

### ISSUE THREAD

**Issue by jhg03a** [voxpupuli/puppet-yum#53]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.10.1
- Ruby: bundled
- Distribution: CentOS 7
- Module version: 2.0.0

## How to reproduce (e.g Puppet code you use)
Hiera:
```
yum::managed_repos:
    - epel
```
Puppet Profile:
```
  include ::yum
```

## What are you seeing
Instead of a a file being created at /etc/repos.d/epel.repo, it is created at "/etc/yum.repos.d/Extra Packages for Enterprise Linux 7 - $basearch.repo".  

At that point if you try to add a package from epel, such as glances, the yum command will fail.  When trying to run a manual yum install to verify the package exists, you get the error below.
## What behaviour did you expect instead
A functional package install with yum from epel.  It should have payed attention to the target parameter to Yumrepo.
## Output log
```
[jonathan.gray@puppet yum.repos.d]$ sudo yum repolist
Loaded plugins: fastestmirror, versionlock
Bad id for repo: Extra Packages for Enterprise Linux 7 - x86_64, byte =   5
Loading mirror speeds from cached hostfile
 * base: dist1.800hosting.com
 * updates: www.gtlib.gatech.edu
repo id                                                                              repo name                                                                                             status
base/7/x86_64                                                                        CentOS-7 - Base                                                                                       9,363
puppet_enterprise                                                                    PuppetLabs PE Packages 7 - x86_64                                                                        24
updates/7/x86_64                                                                     CentOS-7 - Updates                                                                                    1,857
repolist: 11,244
[jonathan.gray@puppet yum.repos.d]$ sudo vim
CentOS-Base.repo                                        centos-media.repo                                       Extra Packages for Enterprise Linux 7 - $basearch.repo
CentOS-CR.repo                                          CentOS-Media.repo                                       puppet_enterprise.repo
CentOS-Debuginfo.repo                                   CentOS-Sources.repo
CentOS-fasttrack.repo                                   CentOS-Vault.repo
```
## Any additional information you'd like to impart
It looks like this isn't the module's fault but rather the core [YumRepo Resource Type](https://tickets.puppetlabs.com/browse/PUP-2782).  In the meantime it can be worked around by treating epel like a custom repo again.  The gotcha there is you have to give it a new title suffix such as epel_workaround so it doesn't pick up on the broken definitions inside the module.  This also has the limitation that only a single repo definition can be present inside the file.

**Comment by jhg03a** [comment]
It looks like @bastelfreak ran into this [a while ago](https://blog.bastelfreak.de/2014/11/workaround-fuer-yumrepo-resource/) and [worked around it](https://github.com/stephenrjohnson/puppetmodule/pull/79) by just treating .repo files as the ini files they really are and bypassing the Yumrepo resource type all together.

**Comment by crispygoth** [comment]
I think the `target` thing is a bit of a red herring. The issue is that the bundled repo config is using the `name` attribute for the repo description when it should be using the `descr` attribute instead.

I've fixed this in my fork although now I'm having issues with the gpg key. It's trying to read the GPG key from `/etc/pki/rpm-gpg` but this file doesn't exist. Does anyone know how this is intended to work?
