### ISSUE TITLE
Update to puppetlabs/concat 3 or 4

### ISSUE THREAD

**Issue by cristianbalan** [voxpupuli/puppet-yum#66]
Could you please update this module so to support puppetlabs/concat 4 (or at least 3)?
The current advertised dependency of puppetlabs/concat 2 is just connected to the old Puppet 3...

**Comment by cristianbalan** [comment]
Oh, just noticed the duplicate https://github.com/voxpupuli/puppet-yum/issues/57

**Comment by jeefberkey** [comment]
New release coming soon :) https://github.com/voxpupuli/puppet-yum/pull/64
