### ISSUE TITLE
Add support for AmazonLinux 2017

### ISSUE THREAD

**Issue by pillarsdotnet** [voxpupuli/puppet-yum#72]
Added [data/os/Redhat/Amazon.yaml](https://github.com/voxpupuli/puppet-yum/pull/71/files#diff-8a1a2b3cdef4297dc27a254f02b9f783) and modified [metadata.json](https://github.com/voxpupuli/puppet-yum/pull/71/files#diff-490694a9db8f7a371538da1abe484314) to support Amazon Linux 2017.

See https://github.com/voxpupuli/puppet-yum/pull/71

**Comment by ekohl** [comment]
Now that #71 has been merged I think this can be closed. For future reference: if you include ```Closes #71``` in your commit message or even just in the opening message for a PR then github will automatically close it when it's merged.
