### ISSUE TITLE
Hiera 5 warning on puppet 5.3.2

### ISSUE THREAD

**Issue by mterzo** [voxpupuli/puppet-yum#77]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: puppet-agent-5.3.2-1.el7
- Ruby: 2.4.1p111
- Distribution: Centos
- Module version: 2.1.0

## How to reproduce (e.g Puppet code you use)

Just run `puppet apply -e 'class { yum: }'`

## What are you seeing
```
Warning: /opt/aquari/puppet/modules/yum/hiera.yaml: Use of 'hiera.yaml' version 4 is deprecated. It should be converted to version 5
   (in /some/directory/puppet/modules/yum/hiera.yaml)
```
## What behaviour did you expect instead
No warning.

## Any additional information you'd like to impart

Is there a plan for going to hiera 5?

**Comment by bastelfreak** [comment]
Hi @mterzo, thanks for the bug report. Are you able to create a fix for this?
