### ISSUE TITLE
yum::versionlock causes configuration loss

### ISSUE THREAD

**Issue by vchepkov** [voxpupuli/puppet-yum#90]
yum::versionlock should only manage relevant configuration and do not 'purge' existing configuration.
imagine if 'host' resource did the same. Since resource uses 'concat' for implementation it overrides all existing configuration. augeas or file_line would be more appropriate

**Comment by traylenator** [comment]
There is a trade off. It is useful to have things purged when they are un-configured.

Given this file is by default empty and not managed anyway other way letting puppet control the file fully is useful. The solution is not to add lines to the file any other way.  
So this would be a close won't fix from me.
